### ISSUE TITLE
forpost.lviv.ua

### ISSUE THREAD

**Issue by P0Rtvine** [llacb47/miscfilters#11]
`https://forpost.lviv.ua/`

False positive  `?fbclid=$document,important` **Facebook list**

### Screenshot(s)
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/112200060-8517d480-8c17-11eb-8e34-a8f9a7d4ba2a.gif)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: 1.34.0

**Comment by P0Rtvine** [comment]
@llacb47 
`https://itc.ua/`
### Screenshot(s)
<details>
<summary>Gif</summary>

![2021-03-29_175325](https://user-images.githubusercontent.com/57287308/112855641-b0873d00-90b7-11eb-9932-36929a54de05.png)
</details>

**Comment by llacb47** [comment]
I think I will change this to use the `queryprune` approach like @dandelionsprout 's list does.

**Comment by P0Rtvine** [comment]
> I think I will change this to use the `queryprune`

When?

**Comment by llacb47** [comment]
I'm busy but will do it today.

**Comment by llacb47** [comment]
Done. https://github.com/llacb47/miscfilters/commit/2aa2483841af882e89deef6b38d9381c27fbbb54

**Comment by llacb47** [comment]
Sorry for the delay.
