### ISSUE TITLE
Blocks Prime Membership Info Bar

### ISSUE THREAD

**Issue by dividedby** [llacb47/miscfilters#12]
Noticed an issue today while checking out my Prime Membership page. This filter `||amazon.dev^$3p` blocks the top info bar from showing up and pushes the rest of the content on the page down.

https://smile.amazon.com/mc?%2AVersion%2A=1&%2Aentries%2A=0

Here's the page with the filter enabled:
![amazon2](https://user-images.githubusercontent.com/64715420/114256083-4c009380-997d-11eb-9b2c-70a69291f96a.PNG)

Here's the page with the filter disabled:
![amazon](https://user-images.githubusercontent.com/64715420/114256070-38edc380-997d-11eb-96f6-4cff3d6254c5.png)

**Comment by llacb47** [comment]
Looking into this.

**Comment by llacb47** [comment]
Added here https://github.com/llacb47/miscfilters/commit/7a4bd8b0fb75a1d3f78105d2adeb9f15ef7a3497

**Comment by llacb47** [comment]
I temporarily disabled the filter and will remove it later, sorry for the long response time.

**Comment by dividedby** [comment]
Legend, thanks!
