### ISSUE TITLE
kyivpost.com

### ISSUE THREAD

**Issue by P0Rtvine** [llacb47/miscfilters#16]
`https://www.kyivpost.com/ukraine-politics/ukraine-digest-june-24-2.html`

Can I get around this?
### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-06-24_094101](https://user-images.githubusercontent.com/57287308/123214952-82f03b00-d4d0-11eb-9bbd-dc5f96f4b675.png)
</details>

**Comment by llacb47** [comment]
Visible with Googlebot user agent, use https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/ or https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg

This paywall is server-side and cannot be fixed with uBO.

Hope this was helpful.
