### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by P0Rtvine** [llacb47/miscfilters#25]
`https://www.newyorker.com/magazine/2021/08/09/the-epic-style-of-kerry-james-marshall`

<details>
<summary>Screen</summary>

![2021-08-03_212520](https://user-images.githubusercontent.com/57287308/128066962-0f33f5c2-f67f-405e-88c3-be18f0411f31.png)
</details>

**Comment by llacb47** [comment]
#24
