### ISSUE TITLE
chicagobusiness.com

### ISSUE THREAD

**Issue by P0Rtvine** [llacb47/miscfilters#26]
`https://www.chicagobusiness.com/article/20161027/NEWS08/161029883/facebook-says-users-can-t-stop-it-from-using-biometric-data`

<details>
<summary>Screen</summary>

![2021-08-06_221400](https://user-images.githubusercontent.com/57287308/128560608-4b06262c-e3f5-4664-b0cb-14c8f134558b.png)
</details>

**Comment by llacb47** [comment]
Hi,

please test that the filter I added works on your side.

Thank you :)

**Comment by P0Rtvine** [comment]
It's works, Thank you!
