### ISSUE TITLE
www.telecompaper.com

### ISSUE THREAD

**Issue by WoodpeckerBaby** [llacb47/miscfilters#28]
Is it possible to support this domain?

www.telecompaper.com

It seems that the overlay is cosmetic. 

<details>

<img width="1570" alt="ff" src="https://user-images.githubusercontent.com/14303318/135398980-75d19b26-737b-4f91-8beb-a046b8cc589e.png">

</details>

**Comment by llacb47** [comment]
Hi, sorry but it's not possible. Only the abstract (first paragraph) of the article is served in the source code.
