### ISSUE TITLE
Found 4 entries

### ISSUE THREAD

**Issue by DandelionSprout** [llacb47/miscfilters#4]
Paywall at `https://thehardtimes.net/harddrive/the-top-5-comments-on-hard-drive-articles-this-week-2/`.

`/plugins/coil-web-monetization^` seems to work pretty well for me to prevent the paywall from being loaded.

**Comment by DandelionSprout** [comment]
40min after writing the OP, I also found a softwall at `https://www.theladders.com/` (Browse a bit around until the 3-article limit is reached), which could be avoided with `/api/auth/is-logged-in$domain=theladders.com`.

**Comment by DandelionSprout** [comment]
Another one I've come across:
```
! https://www.namibiansun.com/news/no-english-cucumbers-will-be-imported-2020-09-25/
! https://www.az.com.na/nachrichten/darber-spricht-das-fahrerlager-beim-grossen-preis-von-russland2020-09-26/
! https://www.republikein.com.na/nuus/verspreiding-van-sprinkane-intens2020-09-25/
namibiansun.com,az.com.na,republikein.com.na###payModal
namibiansun.com,az.com.na,republikein.com.na##.modal-backdrop
```

**Comment by llacb47** [comment]
I think I got them all. Sorry for the delay, I was a bit busy.

**Comment by DandelionSprout** [comment]
Ah, okay. Then I know that now, at least. 😅
