### ISSUE TITLE
Blocks Customer Support Chat

### ISSUE THREAD

**Issue by dividedby** [llacb47/miscfilters#6]
I've been trying out your Amazon annoyances list and I noticed that this filter `amazon.*##[role="banner"]>*:not(br)` hides the customer support chat.

https://smile.amazon.com/gp/help/customer/contact-us

Here's the page with the filter enabled:
![image](https://user-images.githubusercontent.com/64715420/102899881-32b8f300-4431-11eb-835d-37ebd6492987.png)

And here's without the filter enabled:
![image](https://user-images.githubusercontent.com/64715420/102900014-5a0fc000-4431-11eb-8738-94dd9804a86b.png)

**Comment by llacb47** [comment]
Thanks for reporting! Are you liking the amazon list so far? I didn't know anyone even used it, lol.

**Comment by dividedby** [comment]
Seems to be working well, this was the only thing I noticed that was “broken” but I’ll have to do some side by side testing. Amazon can be such a mess so anything to tame it is a win in my book!
